### Desde listas o tuplas

Convierte listas y tuplas de Python en arrays NumPy. Muy útil para comenzar a trabajar con tus propios datos.

In [2]:
import numpy as np

# Array de una dimensión (1D)
a1 = np.array([1, 2, 3, 4])
print(a1)

[1 2 3 4]


In [3]:
# Array de dos dimensiones (2D)
a2 = np.array([[1, 2], [3, 4]])
print(a2)


[[1 2]
 [3 4]]


### Con funciones de NumPy

NumPy ofrece varias funciones para crear arrays rápidamente, ideales para pruebas, inicialización y generación de datos sintéticos.

In [4]:
# arange: secuencia de números
arr = np.arange(0, 6)
print(arr)


[0 1 2 3 4 5]


In [5]:
# zeros y ones
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


2. Cambiar la forma de un array (reshape)

In [6]:
arr = np.arange(6)
reshaped = arr.reshape((2, 3))
print(reshaped)

[[0 1 2]
 [3 4 5]]


## 3. Concatenar arrays
Unir arrays puede hacerse horizontal o verticalmente.

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Vertical (añadir filas)
v_concat = np.vstack((a, b))
print(v_concat)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
# Horizontal (añadir columnas)
c = np.array([[7], [8], [9]])
h_concat = np.hstack((v_concat, c))
print(h_concat)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [9]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
xy = np.concatenate([x, y])
print(xy)

[1 2 3 4 5 6]


## 4. Operaciones básicas con arrays

In [10]:
arr = np.array([2, 4, 6, 8])

# Suma y resta
print(arr + 1)
print(arr - 1)

# Multiplicación y división
print(arr * 2)
print(arr / 2)

# Potencias y raíz
print(arr ** 2)
print(np.sqrt(arr))

[3 5 7 9]
[1 3 5 7]
[ 4  8 12 16]
[1. 2. 3. 4.]
[ 4 16 36 64]
[1.41421356 2.         2.44948974 2.82842712]


Operaciones entre arrays:

In [11]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a * b)

[11 22 33]
[10 40 90]
