## 1. Operaciones estadísticas básicas

### Promedio (`mean`), desviación estándar (`std`), suma (`sum`)

Estas funciones permiten obtener estadísticas rápidas sobre los datos contenidos en un array.


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr))

3.0
1.4142135623730951
15


Para arrays multidimensionales, se puede especificar el eje (`axis`) sobre el cual calcular:

In [3]:
mat = np.array([[1, 2], [3, 4]])

print(np.mean(mat, axis=0))
print(np.mean(mat, axis=1))

[2. 3.]
[1.5 3.5]


## 2. Generación de datos: `arange`, `linspace`, `random`

### `arange` y `linspace`

Estas funciones crean arrays numéricos con distintos criterios:


In [2]:
# arange: números enteros (o decimales) en un rango
a = np.arange(0, 10, 2)
print(a)

# linspace: números equiespaciados entre dos valores
b = np.linspace(0, 1, 5)
print(b)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Datos aleatorios con `random`

NumPy incluye funciones para generar números aleatorios, útiles para simulaciones y pruebas.

In [10]:
rng = np.random.default_rng(42)

# Array aleatorio de 3 números entre 0 y 1
rand_arr = rng.random(3)
print(rand_arr)

# Array aleatorio entero entre 0 y 9, forma (2, 2)
rand_int = rng.integers(0, 10, size=(2, 2))
print(rand_int)

[0.77395605 0.43887844 0.85859792]
[[0 6]
 [2 0]]


## 3. Álgebra lineal

NumPy tiene funciones avanzadas para trabajar con matrices y resolver problemas de álgebra lineal.

### Producto de matrices


In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# Producto matricial
prod = np.dot(A, B)
print(prod)

[[ 4  4]
 [10  8]]


Desde Python 3.5 también se puede usar el operador `@` para multiplicación de matrices:

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print(A @ B)

[[ 4  4]
 [10  8]]


### Transpuesta y determinante

In [7]:
print(A.T)
print(np.linalg.det(A))

[[1 3]
 [2 4]]
-2.0000000000000004


### Inversa de una matriz

In [8]:
invA = np.linalg.inv(A)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]


### Solución de sistemas lineales

In [9]:
# Ax = b
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)

[-4.   4.5]
